import html
def e(x):return html.escape("" if x is None else str(x))
def build_dashboard_html(d):
    o=d.get("overall",{});bad=o.get("fingerprintMismatch",False);status="BUILD MISMATCH" if bad else ("READY FOR REVIEW" if not o.get("failed") and not d.get("incompleteModules") else "ATTENTION REQUIRED")
    b=d.get("builds",[{}])[0] if d.get("builds") else {}
    builds=d.get("builds",[])
    build="<div class='grid'>"+''.join(f"<div><label>{k}</label><strong>{e(v)}</strong></div>" for k,v in {
      "Fingerprint":b.get("fingerprint","Not detected"),"Android":b.get("androidVersion","Not detected"),"Security Patch":b.get("securityPatch","Not detected"),
      "Build ID":b.get("buildId","Not detected"),"SDK":b.get("sdk","Not detected"),"Architecture":b.get("abis","Not detected")}.items())+"</div>"
    if bad:
        build="<table><tr><th>Build</th><th>Suites</th><th>Fingerprint</th><th>Android</th><th>Patch</th></tr>"+''.join(
          f"<tr><td>Build {chr(65+i)}</td><td>{e(', '.join(x.get('suites',[])))}</td><td>{e(x.get('fingerprint'))}</td><td>{e(x.get('androidVersion'))}</td><td>{e(x.get('securityPatch'))}</td></tr>" for i,x in enumerate(builds))+"</table>"
    rows="" if bad else ''.join(f"<tr><td><b>{e(x['name'])}</b></td><td>{x['modules']}</td><td>{x['completedModules']}</td><td>{max(0,x['modules']-x['completedModules'])}</td><td>{x['passed']}</td><td>{x['failed']}</td><td>{x['assumptionFailures']}</td><td>{x['ignored']}</td><td>{x['testCases']}</td></tr>" for x in d.get("suites",[]))
    issues="" if bad else "<div class='two'><div><h2>Incomplete Modules</h2>"+("".join(f"<div class='issue'><b>{e(x['suite'])} · {e(x['module'])}</b><small>{e(x['reason'])}</small></div>" for x in d.get("incompleteModules",[])) or "<p class='ok'>No incomplete modules.</p>")+"</div><div><h2>Failed Test Cases</h2>"+("".join(f"<div class='issue'><b>{e(x['suite'])} · {e(x['module'])} · {e(x['testCase'])}</b><small>{e(x['details'])}</small></div>" for x in d.get("failures",[])) or "<p class='ok'>No failed test cases.</p>")+"</div></div>"
    suite="" if bad else f"<section><h2>Suite Summary</h2><table><tr><th>Suite</th><th>Mods</th><th>Done</th><th>Inc</th><th>Passed</th><th>Failed</th><th>Assumption</th><th>Ignored</th><th>Total</th></tr>{rows}</table></section>"
    return f"""<!doctype html><html><head><meta charset='utf-8'><title>GCT Certification Dashboard</title><style>
body{{font:14px Arial;margin:0;background:#f3f5f8;color:#172033}}main{{max-width:1100px;margin:auto;padding:25px}}header{{background:linear-gradient(120deg,#172554,#2563eb,#7c3aed);color:#fff;padding:28px;border-radius:14px;display:flex;justify-content:space-between}}section{{background:#fff;margin-top:16px;padding:20px;border:1px solid #dfe5ef;border-radius:12px}}h1{{margin:0}}h2{{color:#172554;font-size:16px}}table{{width:100%;border-collapse:collapse;overflow:auto}}th,td{{padding:10px;border-bottom:1px solid #edf0f5;text-align:left}}th{{background:#eef4ff;font-size:11px}}.grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}}.grid div{{border:1px solid #dfe5ef;padding:12px}}label,small{{display:block;color:#667085;font-size:11px;margin-bottom:5px}}.two{{display:grid;grid-template-columns:1fr 1fr;gap:16px}}.issue{{padding:10px;border-left:4px solid #dc2626;background:#fffafa;margin:7px 0}}.ok{{color:#047857;background:#e9f9f2;padding:10px}}@media(max-width:700px){{.grid,.two{{grid-template-columns:1fr}}header{{display:block}}}}</style></head><body><main><header><div><h1>GCT Report Parser</h1><p>Certification Intelligence Dashboard</p></div><b>{e(status)}</b></header><section><h2>Build Information</h2>{build}</section>{suite}{issues}<p style='text-align:center;color:#667085;font-size:11px'>Generated {e(d.get("generatedAt"))} · Internal Certification Tool</p></main></body></html>"""
